### ISSUE TITLE
What do you mean by "queries"?

### ISSUE THREAD

**Issue by nutellamok** [MSU-MLSys-Lab/arch2vec#1]
In the Experiments section of your paper, you keep referring to "queries" or the number of "queried" architectures, but I'm not entirely sure of what you mean by that... ex) Table 2 shows the search performance comparison in terms of number of architecture queries.

Could you clarify what "architecture queries" are specifically  in the context of the architecture search process?

**Comment by shenyann** [comment]
Hi, the number of queries means the number of sampled architectures. The meta controller (in this work the policy net in REINFORCE and the Bayesian linear regression in DNGO) outputs the most promising architectures in each iteration, and these architectures (queries) are used for the full evaluation.
